config:
  image_grid_width_sm: 640
  image_grid_width_md: 1080
  image_grid_width_lg: 1800
  image_width_sm: 1080
  image_width_md: 1800
  image_width_lg: 2400
  font_stack_system: >-
    -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu,
    Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", Arial, sans-serif,
    "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"
metadata:
  site_url: 'https://astounding-cocada-2ef2aa.netlify.app/'
  site_title: nancy elle
  site_subtitle_1: paint & film
  site_subtitle_2: 'atlanta, ga'
  site_description: >
    nancy is currently:

    photographing and writing bimonthly visual diary entries on
    [Substack](https://nancyelle.substack.com/).

    researching, scripting, and recording art history essays for [ART
    BLANCHE](https://open.spotify.com/show/4LmTpL9oSsXrFAABL4raOl?si=d7c2263e4b584e13).


    you can contact her at:  

    hello\@nancyelle.com

    instagram: @[nancyelle\_](https://instagram.com/nancyelle_)
  site_email: hello@nancyelle.com
  site_social_url: 'http://instagram.com/nancyelle_'
  site_icon_svg: /assets/uploads/favicon.svg
  site_icon_png: ''
  site_ga4_id: ''
  seo:
    site_title: Halide - Jamstack portfolio theme
    site_description: >-
      A customizable, minimalist portfolio website designed for photographers
      and still image creators.
    no_index: false
theme:
  theme_layout:
    space_scale: 100
  theme_colors:
    background: '#ffffff'
    text: '#101010'
    link: '#542BFF'
    background_dark: '#101010'
    text_dark: '#E1E1E1'
    link_dark: '#FFFFFF'
  theme_typography:
    font: Overpass Mono
    font_weight: 400
    font_scale: 100
    line_height_scale: 100
  theme_features:
    enable_dark_mode: true
    item_output_limit: 48
    transition_duration: 300
    show_project_year: true
    show_project_grid_titles: true
images:
  avif:
    enabled: false
  webp:
    enabled: true
    quality: 75
  jpeg:
    enabled: true
    quality: 75
i18n:
  site_language: en
  site_social_title: GitHub
